version: '3.8'

services:
  backend:
    build: ./backEndAppDayana
    container_name: backEndAppDayana
    ports:
      - "3000:3000"
    volumes:
      - ./backEndAppDayana:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development

  frontend:
    build: ./frontAppDaya
    container_name: frontAppDaya
    ports:
      - "5173:5173"
    volumes:
      - ./frontAppDaya:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
    depends_on:
      - backend