name: Run Backend Tests

on:
  push:
    branches: [ '**' ]
  pull_request:
    branches: [ main ]
  push:
    branches:
      - main


jobs:
  run-api-tests:
    runs-on: ubuntu-latest

    steps:
      - name: 📦 Code checkout
        uses: actions/checkout@v4

      - name: Installing dependencies
        run: npm install


      - name: 📥 Cypress tests run
        uses: cypress-io/github-action@v6
        with:
          start: npm run start:api       
          wait-on: http://localhost:3000 
          wait-on-timeout: 120           
          command: npx cypress run --spec "cypress/e2e/api/**/*.cy.js"

